name: Generate Documentation

on:
  push:
    branches:
      - main  # Change to the branch you want to trigger the action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify the Python version to use

      - name: Install Dependencies
        run: |
          pip install pdoc matplotlib pandas seaborn torch utils  # Add other dependencies as needed

      - name: Generate Documentation
        run: |
          pdoc --output-dir docs ./src ./benchmark ./examples ./test  # Generate documentation for specified modules

      - name: Upload Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
