name: Generate Documentation

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify the Python version

      - name: Install Dependencies
        run: |
          pip install pdoc matplotlib pandas seaborn torch utils  # Ensure all dependencies are correctly specified

      - name: Generate Documentation
        run: |
          mkdir -p docs  # Create the docs directory if it doesn't exist
          pdoc --output-dir docs ./src ./benchmark ./examples ./test --force  # Include all specified module paths and force generation

      - name: Upload Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
